# Generated by Django 5.2.17 on 2026-08-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_pickup_distance_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("en-route", "En route"),
                    ("pickup", "Pickup"),
                    ("dropoff", "Dropoff"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rideevent",
            name="ride",
            field=models.ForeignKey(
                db_column="id_ride",
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ride_events",
                to="rides.ride",
            ),
        ),
    ]
