# Generated by Django 5.2.17 on 2026-08-13 06:37

import rides.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_status_alter_rideevent_ride'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', rides.models.UserManager()),
            ],
        ),
    ]
